name: skantest
dependencies:
- python>=3.6*
- setuptools>=19.6*
- numba>=0.29
- numpy>=1.11*
- numpydoc>=0.5*
- scipy>=1.0*
- scikit-image>=0.14*
- networkx>=2.0*
- matplotlib>=3.0.2*
- pandas>=0.24*
- openpyxl>=2.4*
- xlrd>=1.0*
- pytest>=3*
- coverage>=4.0
- pytest-cov>=2.2
- click>=0.5
- pip:
  - tifffile>=2019.*
  - hypothesis>=3.6
  - imageio>=2.0
  - tqdm>=4.11
  - nose>=1.3
  - nb2plots>=0.5
  - sphinx_rtd_theme
  - seaborn>=0.9
